# CaseOpening Configuration
messages:
  prefix: "&8[&6Crates&8] "
  no-permission: "%prefix%&cYou don't have permission to do this!"
  key-received: "%prefix%&aYou received &e%amount% %key_name% &akeys!"
  crate-placed: "%prefix%&aCrate has been placed successfully!"
  crate-removed: "%prefix%&cCrate has been removed!"
  crate-destroyed: "%prefix%&cCrate has been destroyed!"
  not-enough-keys: "%prefix%&cYou don't have enough keys to open this crate!"
  no-key: "%prefix%&cYou need a key to open this crate!"
  wrong-key: "%prefix%&cThis is not the correct key for this crate!"
  configs-reloaded: "%prefix%&aAll configurations have been reloaded!"
  reload-error: "%prefix%&cError reloading configurations! Check console for details."
  insufficient-funds: "%prefix%&cYou don't have enough money!"
  purchase-success: "%prefix%&aSuccessfully purchased %amount% %key_name% key(s)!"
  already-opening: "&cYou are already opening a case!"
  reward-won: "%prefix%&aYou won: &e%reward_name%&a!"

# GUI Settings
gui:
  # Opening Animation GUI
  opening:
    title: "&8Opening %crate_name%"
    filler-material: BLACK_STAINED_GLASS_PANE
    filler-name: " "
  
  # Contents Preview GUI
  contents:
    title: "&8%crate_name% Contents"
    filler-material: BLACK_STAINED_GLASS_PANE
    filler-name: " "
    reward-display:
      lore:
        - ""
        - "&7Chance: &e%chance%%"
        - "&7Amount: &e%amount%"
        - "&7Type: %reward_type%"
      type-formats:
        money: "&a&lMoney Reward"
        command: "&d&lSpecial Reward"
        item: "&b&lItem Reward"
    more-rewards:
      name: "&e&lMore Rewards..."
      lore:
        - "&7There are &e%remaining_rewards% &7more rewards"
        - "&7that are not shown here."

# Hologram Settings
hologram:
  offset: 2.5
  lines:
    - "&e%crate_name%"
    - "&eRight Click to open"
    - "&eLeft Click to view contents"

# Shop Configuration
shop:
  settings:
    title: "&8Key Shop"
    fill-empty: true
    filler-material: BLACK_STAINED_GLASS_PANE

# Key Settings
keys:
  shop_lore:
    - "&7Price: &a$%price%"
    - "&7Amount: &e%amount%"
    - ""
    - "&eClick to purchase!"